apiVersion: v1
kind: Service
metadata:
  name: policyserver
spec:
  selector:
    app: policyserver
  ports:
    - name: grpc-tyk
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
